### ISSUE TITLE
AttributeError: 'dict' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by sealj553** [purduesigbots/pros-cli2#61]
#### Expected Behavior:
Running `pros make template` in a freshly-cloned pros directory builds the template project.
#### Actual Behavior:
The following error is shown:
```
Traceback (most recent call last):
  File "/usr/bin/pros", line 11, in <module>
    load_entry_point('pros-cli', 'console_scripts', 'pros')()
  File "/home/jackson/git/pros-cli/proscli/main.py", line 9, in main
    cli.main(prog_name='pros')
  File "/usr/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jackson/git/pros-cli/proscli/build.py", line 26, in make
    cfg = prosconfig.ProjectConfig(prosconfig.ProjectConfig.find_project('.'))
  File "/home/jackson/git/pros-cli/prosconfig/__init__.py", line 82, in __init__
    super(ProjectConfig, self).__init__(file, error_on_decode=raise_on_error)
  File "/home/jackson/git/pros-cli/prosconfig/__init__.py", line 25, in __init__
    self.__dict__.update(jsonpickle.decode(f.read()).__dict__)
AttributeError: 'dict' object has no attribute '__dict__'
```
running `make template` works fine.
#### System information:
Operating System:  Arch Linux
PROS Version: 2.6.1

#### Additional Information
This looks like a possible fix: https://stackoverflow.com/a/41672053/7112567

**Comment by edjubuh** [comment]
Can you post the content of the project.pros inside your PROS project?

**Comment by sealj553** [comment]
It's the default from [pros](https://github.com/purduesigbots/pros)
````
{
    "py/object": "pros.conductor.project.Project",
    "py/state": {
        "project_name": "hello",
        "target": "cortex",
        "templates": { },
        "upload_options": {}
    }
}
````

**Comment by edjubuh** [comment]
It looks like this project was created with PROS 3 and you're working with it in PROS 2. Is that correct?

**Comment by sealj553** [comment]
I'm not sure which version the project was created with, but it's the 'template' project from the pros master branch along with pros-cli (2).
I can compile as is with just `make template`, but would you recommend using pros cli-3-support branch along with pros-cli3?

**Comment by edjubuh** [comment]
PROS CLI 2.x.x doesn't currently have forward compatibility with projects created with PROS CLI 3.x.x. That's not something we're currently interested in implementing, but would be open to a pull request which supports this.

**Comment by sealj553** [comment]
It appears that this error is caused by a python syntax error, not anything directly relating to project files. I figured it should be a simple fix on line 25 of `prosconfig/__init__.py` but I don't have much experience with python.
