### ISSUE TITLE
Error with python before flashing occurs

### ISSUE THREAD

**Issue by GLMONTER** [purduesigbots/pros-cli2#64]
#### Expected Behavior:
For my program to flash to the cortex
#### Actual Behavior:
The program fails to flash with python errors
#### Steps to reproduce:
follow the install instructions for mac os, then try to flash a program to the Vex Cortex
#### System information:
Mac OS Mojave

PROS Version: (run `pros --version`)
2.6.1
#### Additional Information
Here is the output
#### Screenshots/Output Dumps/Stack MONTERs-MacBook-Pro:DEMOLISH monter$ pros flash -f "/Users/monter/Documents/Dev/DEMOLISH"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/pros", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/proscli/main.py", line 9, in main
    cli.main(prog_name='pros')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func

    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: flash() got an unexpected keyword argument 'file'

**Comment by HotelCalifornia** [comment]
sorry for the delayed response. out of curiosity, does it work if you specify `--binary`, `--file`, or `-b` instead of `-f`?

**Comment by GLMONTER** [comment]
Yes I have tried that, I ended up installing pros-editor so I can work with my V5 and Cortex at the same time and it seems to work, but to use the CLI 2 and Atom I had to change the flasher.py file.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by HotelCalifornia** [comment]
Gotcha. Our current and future development efforts are mostly going to be concerned with the new version of the CLI, so if using that has been working ok, I'm going to close this issue.
